"""Initial migrations

Revision ID: 1868901d8ff9
Revises: 
Create Date: 2026-02-10 17:25:07.126352

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1868901d8ff9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('organization_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('inn')
    )
    op.create_table('staff_members',
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=False),
    sa.Column('staff_role', sa.Enum('MANAGER', 'TECHNICAL_SUPPORT', 'DUTY_ENGINEER', 'ADMINISTRATOR', name='staffrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('backup_manager_1_id', sa.BigInteger(), nullable=True),
    sa.Column('backup_manager_2_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['backup_manager_1_id'], ['staff_members.tg_user_id'], ),
    sa.ForeignKeyConstraint(['backup_manager_2_id'], ['staff_members.tg_user_id'], ),
    sa.PrimaryKeyConstraint('tg_user_id')
    )
    op.create_table('users',
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('registration_status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', name='registrationstatus'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'EXPIRED', 'NONE', name='subscriptionstatus'), nullable=False),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('notification_preferences', sa.Boolean(), nullable=False),
    sa.Column('default_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('last_nps_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_manager_id'], ['staff_members.tg_user_id'], ),
    sa.PrimaryKeyConstraint('tg_user_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('gs_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_number', sa.String(length=32), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('conflict_status', sa.Enum('NONE', 'PENDING_REVIEW', 'RESOLVED', name='keyconflictstatus'), nullable=False),
    sa.Column('conflict_reported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tg_user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_number')
    )
    op.create_table('manager_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_inn', sa.String(length=12), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['staff_members.tg_user_id'], ),
    sa.ForeignKeyConstraint(['organization_inn'], ['organizations.inn'], ),
    sa.ForeignKeyConstraint(['tg_user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id', 'organization_inn', name='uq_user_org_assignment')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_type', sa.Enum('INVOICE', 'TECHNICAL_SUPPORT', 'RENEWAL', name='tickettype'), nullable=False),
    sa.Column('ticket_status', sa.Enum('NEW', 'IN_PROGRESS', 'WAITING_CLIENT', 'CLOSED', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('organization_inn', sa.String(length=12), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('delivery_method', sa.Enum('TELEGRAM', 'EMAIL', 'NONE', name='deliverymethod'), nullable=False),
    sa.Column('delivery_email', sa.String(length=256), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff_members.tg_user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_inn'], ['organizations.inn'], ),
    sa.ForeignKeyConstraint(['tg_user_id'], ['users.tg_user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_inn', sa.String(length=12), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_inn'], ['organizations.inn'], ),
    sa.ForeignKeyConstraint(['tg_user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id', 'organization_inn', name='uq_user_organization')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('USER', 'STAFF', 'SYSTEM', name='sendertype'), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'PHOTO', 'DOCUMENT', 'VOICE', 'SYSTEM_NOTIFICATION', name='messagetype'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['gs_keys.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'key_id', name='uq_ticket_key')
    )
    op.create_table('file_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.Enum('PDF', 'IMAGE', 'DOCUMENT', 'OTHER', name='filetype'), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=256), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_type', sa.Enum('USER', 'STAFF', name='uploadertype'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_attachments')
    op.drop_table('ticket_keys')
    op.drop_table('messages')
    op.drop_table('user_organizations')
    op.drop_table('tickets')
    op.drop_table('manager_assignments')
    op.drop_table('gs_keys')
    op.drop_table('users')
    op.drop_table('staff_members')
    op.drop_table('organizations')
    # ### end Alembic commands ###
