"""add_staff_activated_action_type

Revision ID: 4823f153f995
Revises: add_escalations_table
Create Date: 2026-02-24 17:16:32.341094

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4823f153f995'
down_revision: str | Sequence[str] | None = 'add_escalations_table'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_rules_date_range'), table_name='calendar_rules')
    op.drop_index(op.f('ix_calendar_rules_priority_created'), table_name='calendar_rules')
    op.alter_column('escalations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_escalations_is_resolved_created_at'), table_name='escalations')
    op.alter_column('tickets', 'escalation_task_reminder_id',
               existing_type=sa.VARCHAR(length=255),
               comment='ID Celery задачи напоминания',
               existing_nullable=True)
    op.alter_column('tickets', 'escalation_task_escalation_id',
               existing_type=sa.VARCHAR(length=255),
               comment='ID Celery задачи эскалации',
               existing_nullable=True)
    op.alter_column('tickets', 'is_escalated',
               existing_type=sa.BOOLEAN(),
               comment='Флаг эскалированной заявки',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'is_escalated',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг эскалированной заявки',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tickets', 'escalation_task_escalation_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID Celery задачи эскалации',
               existing_nullable=True)
    op.alter_column('tickets', 'escalation_task_reminder_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID Celery задачи напоминания',
               existing_nullable=True)
    op.create_index(op.f('ix_escalations_is_resolved_created_at'), 'escalations', ['is_resolved', 'created_at'], unique=False)
    op.alter_column('escalations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_calendar_rules_priority_created'), 'calendar_rules', [sa.literal_column('rule_priority DESC'), sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_calendar_rules_date_range'), 'calendar_rules', ['start_date', 'end_date'], unique=False)
    # ### end Alembic commands ###
