"""Add missing tables and constraints

Revision ID: 4c1aba65e0c8
Revises: 1868901d8ff9
Create Date: 2026-02-10 17:43:26.684222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c1aba65e0c8'
down_revision: Union[str, Sequence[str], None] = '1868901d8ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('work_mode', sa.Enum('REGULAR', 'EXTENDED', 'NON_WORKING', name='workmode'), nullable=False),
    sa.Column('work_start_time', sa.Time(), nullable=True),
    sa.Column('work_end_time', sa.Time(), nullable=True),
    sa.Column('rule_priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_staff_id', sa.BigInteger(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('broadcast_status', sa.Enum('DRAFT', 'SENDING', 'COMPLETED', 'FAILED', name='broadcaststatus'), nullable=False),
    sa.Column('target_user_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['staff_members.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcast_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ),
    sa.ForeignKeyConstraint(['tg_user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broadcast_id', 'tg_user_id', name='uq_broadcast_user_delivery')
    )
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.Enum('TICKET_CREATED', 'TICKET_ASSIGNED', 'TICKET_ESCALATED', 'TICKET_CLOSED', 'STATUS_CHANGED', 'MESSAGE_SENT', 'FILE_UPLOADED', 'USER_REGISTERED', 'KEY_CONFLICT_DETECTED', name='actiontype'), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_id', sa.BigInteger(), nullable=True),
    sa.Column('action_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.tg_user_id'], ),
    sa.ForeignKeyConstraint(['tg_user_id'], ['users.tg_user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('RENEWAL_REMINDER_30', 'RENEWAL_REMINDER_7', 'NPS_SURVEY', name='eventtype'), nullable=False),
    sa.Column('event_status', sa.Enum('SCHEDULED', 'SENT', 'FAILED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('related_ticket_id', sa.Integer(), nullable=True),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['tg_user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('file_attachments_ticket_id_fkey', 'file_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'file_attachments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_ticket_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ticket_keys_ticket_id_fkey', 'ticket_keys', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_keys', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tickets_assigned_staff_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_tg_user_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'tickets', 'staff_members', ['assigned_staff_id'], ['tg_user_id'], ondelete='SET NULL')
    
    # Task 10.2: Add custom CHECK constraints
    # INN format validation (10 or 12 digits)
    op.create_check_constraint(
        'ck_organizations_inn_format',
        'organizations',
        "inn ~ '^[0-9]{10}$' OR inn ~ '^[0-9]{12}$'"
    )
    
    # Phone number format validation
    op.create_check_constraint(
        'ck_users_phone_format',
        'users',
        "phone_number ~ '^\\+?[0-9]{10,15}$'"
    )
    
    # Key number format validation
    op.create_check_constraint(
        'ck_gs_keys_key_format',
        'gs_keys',
        "key_number ~ '^[A-Z]{2}[0-9]{6}$'"
    )
    
    # Escalation level validation (0, 1, or 2)
    op.create_check_constraint(
        'ck_tickets_escalation_level',
        'tickets',
        'escalation_level IN (0, 1, 2)'
    )
    
    # Calendar rules: end_date >= start_date
    op.create_check_constraint(
        'ck_calendar_rules_date_range',
        'calendar_rules',
        'end_date >= start_date'
    )
    
    # Task 10.3: Add indexes for performance
    # Indexes on foreign key columns
    op.create_index('ix_users_default_manager_id', 'users', ['default_manager_id'])
    op.create_index('ix_gs_keys_tg_user_id', 'gs_keys', ['tg_user_id'])
    op.create_index('ix_gs_keys_conflict_status', 'gs_keys', ['conflict_status'])
    op.create_index('ix_manager_assignments_manager_id', 'manager_assignments', ['manager_id'])
    op.create_index('ix_manager_assignments_tg_user_id_organization_inn', 'manager_assignments', ['tg_user_id', 'organization_inn'])
    op.create_index('ix_tickets_tg_user_id', 'tickets', ['tg_user_id'])
    op.create_index('ix_tickets_assigned_staff_id', 'tickets', ['assigned_staff_id'])
    op.create_index('ix_tickets_organization_inn', 'tickets', ['organization_inn'])
    op.create_index('ix_messages_ticket_id', 'messages', ['ticket_id'])
    op.create_index('ix_file_attachments_ticket_id', 'file_attachments', ['ticket_id'])
    op.create_index('ix_file_attachments_message_id', 'file_attachments', ['message_id'])
    op.create_index('ix_action_logs_ticket_id', 'action_logs', ['ticket_id'])
    op.create_index('ix_action_logs_tg_user_id', 'action_logs', ['tg_user_id'])
    op.create_index('ix_action_logs_staff_id', 'action_logs', ['staff_id'])
    op.create_index('ix_notification_events_tg_user_id', 'notification_events', ['tg_user_id'])
    op.create_index('ix_notification_events_related_ticket_id', 'notification_events', ['related_ticket_id'])
    op.create_index('ix_broadcasts_created_by_staff_id', 'broadcasts', ['created_by_staff_id'])
    op.create_index('ix_broadcast_deliveries_broadcast_id', 'broadcast_deliveries', ['broadcast_id'])
    op.create_index('ix_broadcast_deliveries_tg_user_id', 'broadcast_deliveries', ['tg_user_id'])
    
    # Indexes on status/enum columns
    op.create_index('ix_users_registration_status', 'users', ['registration_status'])
    op.create_index('ix_users_subscription_status', 'users', ['subscription_status'])
    op.create_index('ix_staff_members_staff_role', 'staff_members', ['staff_role'])
    op.create_index('ix_staff_members_is_active', 'staff_members', ['is_active'])
    op.create_index('ix_tickets_ticket_status', 'tickets', ['ticket_status'])
    op.create_index('ix_tickets_ticket_type', 'tickets', ['ticket_type'])
    op.create_index('ix_action_logs_action_type', 'action_logs', ['action_type'])
    op.create_index('ix_notification_events_event_type', 'notification_events', ['event_type'])
    op.create_index('ix_notification_events_event_status', 'notification_events', ['event_status'])
    op.create_index('ix_broadcasts_broadcast_status', 'broadcasts', ['broadcast_status'])
    op.create_index('ix_broadcast_deliveries_delivery_status', 'broadcast_deliveries', ['delivery_status'])
    op.create_index('ix_calendar_rules_work_mode', 'calendar_rules', ['work_mode'])
    
    # Indexes on timestamp columns
    op.create_index('ix_users_created_at', 'users', ['created_at'])
    op.create_index('ix_tickets_created_at', 'tickets', ['created_at'])
    op.create_index('ix_messages_sent_at', 'messages', ['sent_at'])
    op.create_index('ix_action_logs_action_timestamp', 'action_logs', ['action_timestamp'])
    op.create_index('ix_notification_events_scheduled_for', 'notification_events', ['scheduled_for'])
    op.create_index('ix_calendar_rules_start_date', 'calendar_rules', ['start_date'])
    op.create_index('ix_calendar_rules_end_date', 'calendar_rules', ['end_date'])
    op.create_index('ix_calendar_rules_rule_priority', 'calendar_rules', ['rule_priority'])
    op.create_index('ix_broadcasts_created_at', 'broadcasts', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes on timestamp columns
    op.drop_index('ix_broadcasts_created_at', 'broadcasts')
    op.drop_index('ix_calendar_rules_rule_priority', 'calendar_rules')
    op.drop_index('ix_calendar_rules_end_date', 'calendar_rules')
    op.drop_index('ix_calendar_rules_start_date', 'calendar_rules')
    op.drop_index('ix_notification_events_scheduled_for', 'notification_events')
    op.drop_index('ix_action_logs_action_timestamp', 'action_logs')
    op.drop_index('ix_messages_sent_at', 'messages')
    op.drop_index('ix_tickets_created_at', 'tickets')
    op.drop_index('ix_users_created_at', 'users')
    
    # Drop indexes on status/enum columns
    op.drop_index('ix_calendar_rules_work_mode', 'calendar_rules')
    op.drop_index('ix_broadcast_deliveries_delivery_status', 'broadcast_deliveries')
    op.drop_index('ix_broadcasts_broadcast_status', 'broadcasts')
    op.drop_index('ix_notification_events_event_status', 'notification_events')
    op.drop_index('ix_notification_events_event_type', 'notification_events')
    op.drop_index('ix_action_logs_action_type', 'action_logs')
    op.drop_index('ix_tickets_ticket_type', 'tickets')
    op.drop_index('ix_tickets_ticket_status', 'tickets')
    op.drop_index('ix_staff_members_is_active', 'staff_members')
    op.drop_index('ix_staff_members_staff_role', 'staff_members')
    op.drop_index('ix_users_subscription_status', 'users')
    op.drop_index('ix_users_registration_status', 'users')
    
    # Drop indexes on foreign key columns
    op.drop_index('ix_broadcast_deliveries_tg_user_id', 'broadcast_deliveries')
    op.drop_index('ix_broadcast_deliveries_broadcast_id', 'broadcast_deliveries')
    op.drop_index('ix_broadcasts_created_by_staff_id', 'broadcasts')
    op.drop_index('ix_notification_events_related_ticket_id', 'notification_events')
    op.drop_index('ix_notification_events_tg_user_id', 'notification_events')
    op.drop_index('ix_action_logs_staff_id', 'action_logs')
    op.drop_index('ix_action_logs_tg_user_id', 'action_logs')
    op.drop_index('ix_action_logs_ticket_id', 'action_logs')
    op.drop_index('ix_file_attachments_message_id', 'file_attachments')
    op.drop_index('ix_file_attachments_ticket_id', 'file_attachments')
    op.drop_index('ix_messages_ticket_id', 'messages')
    op.drop_index('ix_tickets_organization_inn', 'tickets')
    op.drop_index('ix_tickets_assigned_staff_id', 'tickets')
    op.drop_index('ix_tickets_tg_user_id', 'tickets')
    op.drop_index('ix_manager_assignments_tg_user_id_organization_inn', 'manager_assignments')
    op.drop_index('ix_manager_assignments_manager_id', 'manager_assignments')
    op.drop_index('ix_gs_keys_conflict_status', 'gs_keys')
    op.drop_index('ix_gs_keys_tg_user_id', 'gs_keys')
    op.drop_index('ix_users_default_manager_id', 'users')
    
    # Drop CHECK constraints
    op.drop_constraint('ck_calendar_rules_date_range', 'calendar_rules', type_='check')
    op.drop_constraint('ck_tickets_escalation_level', 'tickets', type_='check')
    op.drop_constraint('ck_gs_keys_key_format', 'gs_keys', type_='check')
    op.drop_constraint('ck_users_phone_format', 'users', type_='check')
    op.drop_constraint('ck_organizations_inn_format', 'organizations', type_='check')
    
    # Restore original foreign keys on tickets
    op.drop_constraint('tickets_assigned_staff_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_tg_user_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_tg_user_id_fkey', 'tickets', 'users', ['tg_user_id'], ['tg_user_id'])
    op.create_foreign_key('tickets_assigned_staff_id_fkey', 'tickets', 'staff_members', ['assigned_staff_id'], ['tg_user_id'])
    
    # Restore original foreign keys on ticket_keys
    op.drop_constraint('ticket_keys_ticket_id_fkey', 'ticket_keys', type_='foreignkey')
    op.create_foreign_key('ticket_keys_ticket_id_fkey', 'ticket_keys', 'tickets', ['ticket_id'], ['id'])
    
    # Restore original foreign keys on messages
    op.drop_constraint('messages_ticket_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key('messages_ticket_id_fkey', 'messages', 'tickets', ['ticket_id'], ['id'])
    
    # Restore original foreign keys on file_attachments
    op.drop_constraint('file_attachments_ticket_id_fkey', 'file_attachments', type_='foreignkey')
    op.create_foreign_key('file_attachments_ticket_id_fkey', 'file_attachments', 'tickets', ['ticket_id'], ['id'])
    
    # Drop new tables
    op.drop_table('notification_events')
    op.drop_table('action_logs')
    op.drop_table('broadcast_deliveries')
    op.drop_table('broadcasts')
    op.drop_table('calendar_rules')
    
    # Drop enum types created by this migration
    op.execute('DROP TYPE IF EXISTS workmode CASCADE')
    op.execute('DROP TYPE IF EXISTS actiontype CASCADE')
    op.execute('DROP TYPE IF EXISTS eventtype CASCADE')
    op.execute('DROP TYPE IF EXISTS eventstatus CASCADE')
    op.execute('DROP TYPE IF EXISTS broadcaststatus CASCADE')
    op.execute('DROP TYPE IF EXISTS deliverystatus CASCADE')
    # ### end Alembic commands ###
