"""Added fields to User model

Revision ID: 65143ee6e41d
Revises: change_staff_pk_to_id
Create Date: 2026-02-16 20:21:35.791120

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65143ee6e41d'
down_revision: str | Sequence[str] | None = 'change_staff_pk_to_id'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_logs_action_timestamp'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action_type'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_ticket_id'), table_name='action_logs')
    op.drop_index(op.f('ix_api_retry_queue_status_next_retry'), table_name='api_retry_queue')
    op.drop_index(op.f('ix_broadcast_deliveries_broadcast_id'), table_name='broadcast_deliveries')
    op.drop_index(op.f('ix_broadcast_deliveries_delivery_status'), table_name='broadcast_deliveries')
    op.drop_index(op.f('ix_broadcasts_broadcast_status'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_created_at'), table_name='broadcasts')
    op.drop_index(op.f('ix_calendar_rules_end_date'), table_name='calendar_rules')
    op.drop_index(op.f('ix_calendar_rules_rule_priority'), table_name='calendar_rules')
    op.drop_index(op.f('ix_calendar_rules_start_date'), table_name='calendar_rules')
    op.drop_index(op.f('ix_calendar_rules_work_mode'), table_name='calendar_rules')
    op.drop_index(op.f('ix_file_attachments_message_id'), table_name='file_attachments')
    op.drop_index(op.f('ix_file_attachments_ticket_id'), table_name='file_attachments')
    op.drop_index(op.f('ix_gs_keys_conflict_status'), table_name='gs_keys')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_ticket_id'), table_name='messages')
    op.drop_index(op.f('ix_notification_events_event_status'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_event_type'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_related_ticket_id'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_scheduled_for'), table_name='notification_events')
    op.drop_index(op.f('ix_staff_members_is_active'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_staff_role'), table_name='staff_members')
    op.drop_constraint(op.f('uq_staff_members_tg_user_id'), 'staff_members', type_='unique')
    op.drop_index(op.f('ix_staff_members_tg_user_id'), table_name='staff_members')
    op.create_index(op.f('ix_staff_members_tg_user_id'), 'staff_members', ['tg_user_id'], unique=True)
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_organization_inn'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_type'), table_name='tickets')
    op.alter_column('users', 'tg_user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Telegram user ID (primary key for backward compatibility)',
               existing_nullable=True)
    op.alter_column('users', 'max_user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='MAX messenger user ID (optional)',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_registration_status'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_constraint(op.f('uq_users_tg_user_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'messenger_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('messenger_type', sa.VARCHAR(length=20), server_default=sa.text("'telegram'::character varying"), autoincrement=False, nullable=True, comment='Primary messenger: telegram or max'))
    op.add_column('users', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='Active messenger user ID (used for API calls)'))
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_tg_user_id'), 'users', ['tg_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_index(op.f('ix_users_registration_status'), 'users', ['registration_status'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.alter_column('users', 'max_user_id',
               existing_type=sa.BIGINT(),
               comment='MAX messenger user ID (optional)',
               existing_nullable=True)
    op.alter_column('users', 'tg_user_id',
               existing_type=sa.BIGINT(),
               comment='Telegram user ID (primary key for backward compatibility)',
               existing_nullable=True)
    op.create_index(op.f('ix_tickets_ticket_type'), 'tickets', ['ticket_type'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_status'), 'tickets', ['ticket_status'], unique=False)
    op.create_index(op.f('ix_tickets_organization_inn'), 'tickets', ['organization_inn'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.drop_index(op.f('ix_staff_members_tg_user_id'), table_name='staff_members')
    op.create_index(op.f('ix_staff_members_tg_user_id'), 'staff_members', ['tg_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_staff_members_tg_user_id'), 'staff_members', ['tg_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_staff_members_staff_role'), 'staff_members', ['staff_role'], unique=False)
    op.create_index(op.f('ix_staff_members_is_active'), 'staff_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_notification_events_scheduled_for'), 'notification_events', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notification_events_related_ticket_id'), 'notification_events', ['related_ticket_id'], unique=False)
    op.create_index(op.f('ix_notification_events_event_type'), 'notification_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_events_event_status'), 'notification_events', ['event_status'], unique=False)
    op.create_index(op.f('ix_messages_ticket_id'), 'messages', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_gs_keys_conflict_status'), 'gs_keys', ['conflict_status'], unique=False)
    op.create_index(op.f('ix_file_attachments_ticket_id'), 'file_attachments', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_file_attachments_message_id'), 'file_attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_calendar_rules_work_mode'), 'calendar_rules', ['work_mode'], unique=False)
    op.create_index(op.f('ix_calendar_rules_start_date'), 'calendar_rules', ['start_date'], unique=False)
    op.create_index(op.f('ix_calendar_rules_rule_priority'), 'calendar_rules', ['rule_priority'], unique=False)
    op.create_index(op.f('ix_calendar_rules_end_date'), 'calendar_rules', ['end_date'], unique=False)
    op.create_index(op.f('ix_broadcasts_created_at'), 'broadcasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_broadcasts_broadcast_status'), 'broadcasts', ['broadcast_status'], unique=False)
    op.create_index(op.f('ix_broadcast_deliveries_delivery_status'), 'broadcast_deliveries', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_broadcast_deliveries_broadcast_id'), 'broadcast_deliveries', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_api_retry_queue_status_next_retry'), 'api_retry_queue', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_action_logs_ticket_id'), 'action_logs', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_action_logs_action_type'), 'action_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_logs_action_timestamp'), 'action_logs', ['action_timestamp'], unique=False)
    # ### end Alembic commands ###
